// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using estapar_web_api;

#nullable disable

namespace estapar_web_api.Migrations
{
    [DbContext(typeof(EstaparDbContext))]
    [Migration("20231115200130_CreateFormaPagamentoTable")]
    partial class CreateFormaPagamentoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormaPagamento", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("FormaPagamento");
                });

            modelBuilder.Entity("Garagem", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Preco_1aHora")
                        .HasColumnType("float");

                    b.Property<double>("Preco_HorasExtra")
                        .HasColumnType("float");

                    b.Property<double>("Preco_Mensalista")
                        .HasColumnType("float");

                    b.HasKey("Codigo");

                    b.ToTable("Garagem");
                });
#pragma warning restore 612, 618
        }
    }
}
