// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using estapar_web_api;

#nullable disable

namespace estapar_web_api.Migrations
{
    [DbContext(typeof(EstaparDbContext))]
    partial class EstaparDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormaPagamento", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("FormaPagamento");
                });

            modelBuilder.Entity("Garagem", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Preco_1aHora")
                        .HasColumnType("float");

                    b.Property<double>("Preco_HorasExtra")
                        .HasColumnType("float");

                    b.Property<double>("Preco_Mensalista")
                        .HasColumnType("float");

                    b.HasKey("Codigo");

                    b.ToTable("Garagem");
                });

            modelBuilder.Entity("Passagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarroMarca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarroModelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarroPlaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataHoraSaida")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPagamentoCodigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GaragemCodigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("PrecoTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FormaPagamentoCodigo");

                    b.HasIndex("GaragemCodigo");

                    b.ToTable("Passagem");
                });

            modelBuilder.Entity("Passagem", b =>
                {
                    b.HasOne("FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoCodigo");

                    b.HasOne("Garagem", "Garagem")
                        .WithMany()
                        .HasForeignKey("GaragemCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaPagamento");

                    b.Navigation("Garagem");
                });
#pragma warning restore 612, 618
        }
    }
}
